### ISSUE TITLE
load balancer crashes for big logs

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/AutolabJS#163]
When load balancer receives a result json with very big log, the load balancer crashes with the following output.

```
Error: request entity too large
    at makeError (/load_balancer/node_modules/raw-body/index.js:184:15)
    at module.exports (/load_balancer/node_modules/raw-body/index.js:40:15)
    at read (/load_balancer/node_modules/body-parser/lib/read.js:62:3)
    at jsonParser (/load_balancer/node_modules/body-parser/lib/types/json.js:87:5)
    at Layer.handle [as handle_request] (/load_balancer/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/load_balancer/node_modules/express/lib/router/index.js:317:13)
    at /load_balancer/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/load_balancer/node_modules/express/lib/router/index.js:335:12)
    at next (/load_balancer/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/load_balancer/node_modules/body-parser/lib/types/urlencoded.js:72:36)
```
When that happens, the load balancer restarts and also loses the corresponding execution node from the available pool. Coupled with the tendency of students to submit faulty code for multiple, rapid-fire evaluation requests, we have a scenario where all the execution nodes become unavailable thus bringing the system to a halt.

**Comment by prasadtalasila** [comment]
This is a problem of one of the imported modules. Try updating the imported modules. There is nothing we can do about it.
