### ISSUE TITLE
without git config, deployment tests fail

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/AutolabJS#279]
### Description
On a machine without any git configuration, deployment tests fail. The log is as follows.
```bash
autolabjs@autolabjs-build:~/AutolabJS$ TEST_TYPE=deployment_tests bash tests/test_runner.sh 
+ '[' -d tests/deployment_tests ']'
+ bash tests/deployment_tests/test.sh
+ cd tests/deployment_tests
+ BATS=node_modules/bats/libexec/bats
+ config=./env.conf
+ [[ -f ./env.conf ]]
+ . ./env.conf
++ TMPDIR=/tmp
++ NODE_TLS_REJECT_UNAUTHORIZED=0
++ COMMITPATH=/tmp/gitlab_tests/project
++ GITLABTEMP=/tmp/gitlab_tests/temp
++ GIT_SSL_NO_VERIFY=1
++ GITLAB_DATA=/tmp/gitlab_data
++ NUMBER_OF_EXECUTION_NODES=5
++ INSTALL_DIR=/opt/autolabjs
+ export GIT_SSL_NO_VERIFY NODE_TLS_REJECT_UNAUTHORIZED TESTDIR COMMITPATH
+ export GITLABTEMP TMPDIR GITLAB_DATA NUMBER_OF_EXECUTION_NODES BATS INSTALL_DIR
+ mkdir -p ../backup
+ cp /opt/autolabjs/deploy/configs/main_server/labs.json ../backup/initial_labs.json
+ bash helper_scripts/setup.sh
+ sudo docker exec gitlab sed -i 's/# gitlab_rails\['\''rate_limit_requests_per_period'\''] = 10/gitlab_rails\['\''rate_limit_requests_per_period'\''] = 1000/' /etc/gitlab/gitlab.rb
+ sudo docker exec gitlab gitlab-ctl reconfigure
gitlab Reconfigured!
+ sudo docker exec gitlab gitlab-ctl restart
ok: run: gitaly: (pid 6200) 0s
ok: run: gitlab-monitor: (pid 6218) 1s
ok: run: gitlab-workhorse: (pid 6230) 0s
ok: run: logrotate: (pid 6242) 1s
ok: run: nginx: (pid 6283) 0s
ok: run: node-exporter: (pid 6292) 0s
ok: run: postgres-exporter: (pid 6298) 1s
ok: run: postgresql: (pid 6307) 0s
ok: run: prometheus: (pid 6316) 1s
ok: run: redis: (pid 6327) 0s
ok: run: redis-exporter: (pid 6332) 1s
ok: run: sidekiq: (pid 6338) 0s
ok: run: sshd: (pid 6342) 0s
ok: run: unicorn: (pid 6346) 0s
+ sudo apt-get install -y mysql-client
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  mysql-client-5.7 mysql-client-core-5.7 mysql-common
The following NEW packages will be installed:
  mysql-client mysql-client-5.7 mysql-client-core-5.7 mysql-common
0 upgraded, 4 newly installed, 0 to remove and 31 not upgraded.
Need to get 8,065 kB of archives.
After this operation, 65.8 MB of additional disk space will be used.
Get:1 http://in.archive.ubuntu.com/ubuntu xenial-updates/main amd64 mysql-client-core-5.7 amd64 5.7.21-0ubuntu0.16.04.1 [6,363 kB]
Get:2 http://in.archive.ubuntu.com/ubuntu xenial-updates/main amd64 mysql-common all 5.7.21-0ubuntu0.16.04.1 [15.7 kB]
Get:3 http://in.archive.ubuntu.com/ubuntu xenial-updates/main amd64 mysql-client-5.7 amd64 5.7.21-0ubuntu0.16.04.1 [1,676 kB]
Get:4 http://in.archive.ubuntu.com/ubuntu xenial-updates/main amd64 mysql-client all 5.7.21-0ubuntu0.16.04.1 [10.1 kB]
Fetched 8,065 kB in 5s (1,480 kB/s)
Selecting previously unselected package mysql-client-core-5.7.
(Reading database ... 217131 files and directories currently installed.)
Preparing to unpack .../mysql-client-core-5.7_5.7.21-0ubuntu0.16.04.1_amd64.deb ...
Unpacking mysql-client-core-5.7 (5.7.21-0ubuntu0.16.04.1) ...
Selecting previously unselected package mysql-common.
Preparing to unpack .../mysql-common_5.7.21-0ubuntu0.16.04.1_all.deb ...
Unpacking mysql-common (5.7.21-0ubuntu0.16.04.1) ...
Selecting previously unselected package mysql-client-5.7.
Preparing to unpack .../mysql-client-5.7_5.7.21-0ubuntu0.16.04.1_amd64.deb ...
Unpacking mysql-client-5.7 (5.7.21-0ubuntu0.16.04.1) ...
Selecting previously unselected package mysql-client.
Preparing to unpack .../mysql-client_5.7.21-0ubuntu0.16.04.1_all.deb ...
Unpacking mysql-client (5.7.21-0ubuntu0.16.04.1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up mysql-client-core-5.7 (5.7.21-0ubuntu0.16.04.1) ...
Setting up mysql-common (5.7.21-0ubuntu0.16.04.1) ...
update-alternatives: using /etc/mysql/my.cnf.fallback to provide /etc/mysql/my.cnf (my.cnf) in auto mode
Setting up mysql-client-5.7 (5.7.21-0ubuntu0.16.04.1) ...
Setting up mysql-client (5.7.21-0ubuntu0.16.04.1) ...
+ cd ../../
++ pwd
+ bash scripts/npm_install.sh deployment /home/autolabjs/AutolabJS
+ usage=deployment
+ base_directory=/home/autolabjs/AutolabJS
+ production=("main_server" "main_server/public/js" "load_balancer" "execution_nodes" "util")
+ test=("tests/deployment_tests" "tests/functional_tests" "tests/test_modules")
+ travisTests=("tests/functional_tests" "tests/test_modules")
+ deployment=("tests/deployment_tests" "tests/test_modules")
+ componentPaths=()
+ '[' '!' /home/autolabjs/AutolabJS ']'
+ '[' deployment == production ']'
+ '[' deployment == travis ']'
+ '[' deployment == deployment ']'
+ componentPaths=(${deployment[@]})
+ for i in '"${componentPaths[@]}"'
+ npm install --silent --prefix /home/autolabjs/AutolabJS/tests/deployment_tests
+ for i in '"${componentPaths[@]}"'
+ npm install --silent --prefix /home/autolabjs/AutolabJS/tests/test_modules
++ ls shell
+ tests='concurrent_eval.sh
container.sh
demo_lab.sh
docker_locale.sh
gitlab_en.sh
gitlab.sh
scoreboard.sh
website_load.sh'
+ echo -e '\n Post Install Checks \n'

 Post Install Checks 

+ for test in '$tests'
++ echo concurrent_eval.sh
++ tr _ ' '
++ sed -e 's/\b\(.\)/\u\1/g'
+ testName='Concurrent Eval.Sh'
+ echo -e '\n========== Concurrent Eval Checks =========='

========== Concurrent Eval Checks ==========
+ bash shell/concurrent_eval.sh
+ TESTDIR=execution_node
+ export TESTDIR
+ bash ./helper_scripts/concurrent_eval/concurrent_eval_setup.sh
+ user=("2015A7PS101G" "2015A7PS102G" "2015A7PS201G" "2015A7PS202G" "2015A7PS203G" "2015A7PS204G" "2015A7PS205G")
+ pass=12345678
+ testType=unit_tests
+ labAuthorPath=/tmp/gitlab_data/lab_author
+ studentPath=/tmp/gitlab_data/student
+ '[' -d /tmp/gitlab_data/lab_author ']'
+ '[' -d /tmp/gitlab_data/student ']'
+ bash ./helper_scripts/create_user.sh lab_author 12345678
+ user=lab_author
+ pass=12345678
+ node -e 'User = require("./gitlab.js").User; user = new User("lab_author", "12345678"); user.addUser().catch((e) => {console.log(e); process.exit(1);})'
+ mkdir -p /tmp/gitlab_data/lab_author
+ cp -rf ../../docs/examples/unit_tests/author_solution ../../docs/examples/unit_tests/Driver14.cpp ../../docs/examples/unit_tests/Driver3.py ../../docs/examples/unit_tests/Driver.cpp ../../docs/examples/unit_tests/Driver.java ../../docs/examples/unit_tests/Driver.py ../../docs/examples/unit_tests/execute.sh ../../docs/examples/unit_tests/README.md ../../docs/examples/unit_tests/README.txt ../../docs/examples/unit_tests/student_solution ../../docs/examples/unit_tests/test_cases ../../docs/examples/unit_tests/test_info.txt /tmp/gitlab_data/lab_author
+ bash ./helper_scripts/setup_project.sh lab_author 12345678 lab1 /tmp/gitlab_data/lab_author
+ user=lab_author
+ pass=12345678
+ lab=lab1
+ commitPath=/tmp/gitlab_data/lab_author
+ node -e 'Project = require("./gitlab.js").Project; project = new Project("lab_author", "12345678", "lab1"); project.createProject().catch((e) => {console.log(e); process.exit(1);})'
+ node -e 'Project = require("./gitlab.js").Project; project = new Project("lab_author", "12345678", "lab1"); project.commit("/tmp/gitlab_data/lab_author").catch((e) => {console.log(e); process.exit(1);})'

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'autolabjs@autolabjs-build.(none)')

Error: Commit failed
    at Project.commit (/home/autolabjs/AutolabJS/tests/deployment_tests/gitlab.js:140:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

### Steps to Reproduce

1. Install the AutolabJS
2. Remove the git configuration
3. Run deployment letters

**Expected behavior:** [What you expect to happen]
The deployment tests run with dummy git configuration.

**Actual behavior:** [What actually happens]
The deployment tests fail.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time deployment tests run without git configuration.

**Comment by prasadtalasila** [comment]
PR #286 fixes the issue.
