### ISSUE TITLE
gitlab deployment tests fail

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/AutolabJS#280]
### Description
When run on the installation of gitlab with specific host name / IP address, the deployment tests fail. The logs is as follows.
```
========== Gitlab Checks ==========
+ bash shell/gitlab.sh

> deployment_tests@0.2.0 test /home/autolabjs/AutolabJS/tests/deployment_tests
> mocha -u bdd -R tap --timeout 10000 ./test/

1..10
ok 1 List users on Gitlab List all existing users on Gitlab
ok 2 Add user to gitlab Gitlab does not have the test user before addition
ok 3 Add user to gitlab User is added correctly to Gitlab
ok 4 Add user to gitlab Same user added twice will be rejected
ok 5 Delete user on gitlab Deleting an existing user is successful
ok 6 Delete user on gitlab Deleting a user that does not exist fails
ok 7 Create project for a user on gitlab A new project for a user that does not exist will be rejected
not ok 8 Create project for a user on gitlab A new project is created successfully
  AssertionError: expected { Object (id, description, ...) } to have property 'http_url_to_repo' of 'https://localhost/user/project.git', but got 'https://10.1.9.174/user/project.git'
      at Context.it (test/gitlabTest.js:106:32)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
ok 9 Create project for a user on gitlab Creating a project that exists will be rejected
ok 10 Create a commit on Gitlab Files at the specified path are committed to a project
# tests 10
# pass 9
# fail 1
npm ERR! Test failed.  See above for more details.

```

[Description of the issue]
gitlab deployment tests make a hard assumption that gitlab is installed on the localhost. Even it is so, gitlab has to be available on the network, hence would typically be configured with a specific host name / IP address, instead of localhost

### Steps to Reproduce

1. Install AutolabJS with gitlab host name as anything different from localhost
2. Run the deployment tests

**Expected behavior:** [What you expect to happen]
Deployment tests pass

**Actual behavior:** [What actually happens]
Gitlab deployment tests fail

**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time

**Comment by prasadtalasila** [comment]
The reason for this bug is as follows.
The AutolabJS setup gets installed at /opt/autolabjs directory. But the deployment tests run from a different location, say ~/autolabjs-install directory. Thus the deployment tests do not peruse the configuration settings of the installed AutolabJS.

**Solution?**    
Make the tests aware of the configuration used by the installed version of the autolab. Since the tests already use INSTALL_DIR variable in [env.conf](https://github.com/AutolabJS/AutolabJS/blob/master/tests/deployment_tests/env.conf), we can use the the configuration variables available in the installed AutolabJS

**Comment by prasadtalasila** [comment]
PR #286 fixes the issue.
