### ISSUE TITLE
Execution node crash due to incomplete lab setup

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/AutolabJS#44]
Execution nodes are known to crash under the following conditions.
1. Administrator creates a lab on web application.
2. The corresponding solution repository is not in place on gitlab.
3. Student submits an evaluation request.

When the evaluation request goes to the execution node, the execution node tries to pull the repository from lab_author. Since, it is expecting the existing repository in gitlab, execution node code is not able to handle this exception. Such a possibility should return a different kind of error to the student so that the problem can be taken care of immediately.

Suggestions:
1. Exception handling in execution node.
2. Update of the return codes in execution.sh script.

**Comment by prasadtalasila** [comment]
If the test files are not properly setup for lab_author in gitlab, the I/O testing of DSA-lab kind of scenarios results in the following outcomes.

1. execution node fails
1. student user get blocked

A sample log is given below.

```
2017-02-20T22:50:35.511979966Z { id_no: '2015A7PS001G',
2017-02-20T22:50:35.512012749Z   Lab_No: 'lab0',
2017-02-20T22:50:35.512030455Z   time: '2017-02-20 22:50:35',
2017-02-20T22:50:35.512040878Z   commit: '',
2017-02-20T22:50:35.512052086Z   status: 0,
2017-02-20T22:50:35.512068874Z   penalty: 0,
2017-02-20T22:50:35.512086394Z   socket: 'RyrdGGat1Bcj4oE3AABE',
2017-02-20T22:50:35.512093069Z   language: 'python2' }
2017-02-20T22:50:35.512099423Z bash extract_run.sh 2015A7PS001G lab0 autolab.bits-goa.ac.in "" python2
2017-02-20T22:50:39.299196467Z fs.js:549
2017-02-20T22:50:39.299223911Z   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
2017-02-20T22:50:39.299228493Z                  ^
2017-02-20T22:50:39.299231975Z 
2017-02-20T22:50:39.299235178Z Error: ENOENT: no such file or directory, open '/execution_nodes/submissions/2015A7PS001G/lab0/results/comment.txt'
2017-02-20T22:50:39.299238728Z     at Error (native)
2017-02-20T22:50:39.299251250Z     at Object.fs.openSync (fs.js:549:18)
2017-02-20T22:50:39.299254572Z     at Object.fs.readFileSync (fs.js:397:15)
2017-02-20T22:50:39.299263886Z     at /execution_nodes/execute_node.js:54:22
2017-02-20T22:50:39.299267462Z     at ChildProcess.exithandler (child_process.js:204:7)
2017-02-20T22:50:39.299270577Z     at emitTwo (events.js:87:13)
2017-02-20T22:50:39.299273508Z     at ChildProcess.emit (events.js:172:7)
2017-02-20T22:50:39.299276415Z     at maybeClose (internal/child_process.js:821:16)
2017-02-20T22:50:39.299279433Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

```

**Comment by prasadtalasila** [comment]
PR #184 adds try....catch block to execution_node.js. The returns codes shall not be updated now. The work is postponed to future.
