### ISSUE TITLE
Evaluation of unsupported language does not stop

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/AutolabJS#59]
A client can choose an unsupported language option on the submit page. Here unsupported language means a language that Autolab supports, but not the lab_author. In that case, the front end web application does not terminate the evaluation and the execution node throws up an exception with the following log.

```
{ id_no: 'TSRKPRASAD16',
   Lab_No: 'lab1',
  time: '2016-11-30 09:46:45',
   commit: '',
   status: 0,
   penalty: 0,
   socket: 'vfBzxRE3n4INbBBXAAAH',
   language: 'python2' }
 fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                   ^

 Error: ENOENT: no such file or directory, open '/execution_nodes/submissions/TSRKPRASAD16/lab1/results/log.txt'
     at Error (native)
     at Object.fs.openSync (fs.js:549:18)
     at Object.fs.readFileSync (fs.js:397:15)
     at /execution_nodes/execute_node.js:53:18
     at ChildProcess.exithandler (child_process.js:204:7)
     at emitTwo (events.js:87:13)
     at ChildProcess.emit (events.js:172:7)
     at maybeClose (internal/child_process.js:821:16)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
     ....
```

**Comment by prasadtalasila** [comment]
The execution_node should send back an unsupported language option log message to the client and proceed forward to wait for the next evaluation request.

**Comment by prasadtalasila** [comment]
The problem has been resolved. Closing the issue now.
