### ISSUE TITLE
execution node crash on exception

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/AutolabJS#77]
The execution node crashes when an exception happens in evaluation. The sample log is shown below.

```
requestRun post request recieved
{ id_no: '2010A7PS001G',
  Lab_No: 'lab1',
  time: '2017-02-08 05:14:17',
  commit: '',
  status: 0,
  penalty: 0,
  socket: 'H3n9E-tMvYZJQnDfAAAA',
  language: 'java' }
bash extract_run.sh 2011PHXF011G lab1 10.1.9.208 "" java
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/execution_nodes/submissions/2010A7PS001G/lab1/results/scores.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at /execution_nodes/execute_node.js:53:20
    at ChildProcess.exithandler (child_process.js:220:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by prasadtalasila** [comment]
This happens because the lab_author repository and / or student repository are missing in Gitlab. We should give back sensible results in this case. We should also enable the load balancer and main server to return meaningful message to user and unblock the user.

**Comment by prasadtalasila** [comment]
Above error is also triggered by a run-time error in one of the test cases which results in text files in results/ folder not being updated.

A permanent fix to all these problems is to have exception handling around lines 53 - 55 of [execute_node.js](https://github.com/prasadtalasila/JavaAutolab/blob/master/execution_nodes/execute_node.js).

**Comment by prasadtalasila** [comment]
Sometimes the error looks as follows.

```
Error: ENOENT: no such file or directory, open '/execution_nodes/submissions/2016HT13218/ec1lab/results/comment.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at /execution_nodes/execute_node.js:54:22
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
# localhost:22 SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1
# localhost:22 SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1
# localhost:22 SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1
fatal: destination path 'test' already exists and is not an empty directory.
(node) sys is deprecated. Use util instead.
```

**Comment by prasadtalasila** [comment]
The error happens because of problems in git clone commands. The git clone problems arise either because of client SSH certificate problems or the non-existence of the required repositories.

**Comment by prasadtalasila** [comment]
The problem still persists even after putting in the try...catch block. Even the log remains the same as before. The actual log is shown below.
```shell
2017-08-18T23:16:24.507567940Z bash extract_run.sh 2012A7PS001G test autolab.bits-goa.ac.in "" java
2017-08-18T23:17:03.969194498Z requestRun post request recieved
2017-08-18T23:17:03.970187168Z { id_no: '2012A7PS001G',
2017-08-18T23:17:03.970204475Z   Lab_No: 'lab1',
2017-08-18T23:17:03.970211517Z   time: '2017-08-18 23:17:03',
2017-08-18T23:17:03.970218255Z   commit: '',
2017-08-18T23:17:03.970224624Z   status: 0,
2017-08-18T23:17:03.970230843Z   penalty: 0,
2017-08-18T23:17:03.970236979Z   socket: '_pUURKdO-evrtkr0AAAC',
2017-08-18T23:17:03.970243396Z   language: 'java' }
2017-08-18T23:17:03.970252485Z bash extract_run.sh 2012A7PS001G lab1 autolab.bits-goa.ac.in "" java
2017-08-18T23:17:06.333840954Z fs.js:549
2017-08-18T23:17:06.333880991Z   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
2017-08-18T23:17:06.333887362Z                  ^
2017-08-18T23:17:06.333891183Z 
2017-08-18T23:17:06.333894737Z Error: ENOENT: no such file or directory, open '/execution_nodes/submissions/2012A7PS001G/lab1/results/scores.txt'
2017-08-18T23:17:06.333898720Z     at Error (native)
2017-08-18T23:17:06.333905156Z     at Object.fs.openSync (fs.js:549:18)
2017-08-18T23:17:06.333908956Z     at Object.fs.readFileSync (fs.js:397:15)
2017-08-18T23:17:06.333912551Z     at /execution_nodes/execute_node.js:53:20
2017-08-18T23:17:06.333916153Z     at ChildProcess.exithandler (child_process.js:220:5)
2017-08-18T23:17:06.333919902Z     at emitTwo (events.js:87:13)
2017-08-18T23:17:06.333932680Z     at ChildProcess.emit (events.js:172:7)
2017-08-18T23:17:06.333936700Z     at maybeClose (internal/child_process.js:821:16)
2017-08-18T23:17:06.333940415Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
2017-08-18T23:17:07.018198250Z # autolab.bits-goa.ac.in:22 SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.2
2017-08-18T23:17:07.029866665Z # autolab.bits-goa.ac.in:22 SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.2
2017-08-18T23:17:07.039817864Z # autolab.bits-goa.ac.in:22 SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.2
2017-08-18T23:17:07.052813586Z fatal: destination path 'test' already exists and is not an empty directory.
2017-08-18T23:17:07.216468506Z (node) sys is deprecated. Use util instead.
2017-08-18T23:17:07.248586138Z Listening at 8082
2017-08-18T23:18:33.567256372Z connectionCheck requested
```

Inside the docker containers of execution nodes, the node version is 4.2.6.

**Comment by prasadtalasila** [comment]
The problem exists in the docker container file copy. Dockerfile COPY command copies from master branch instead of the checkedout branch. We are trying to understand the issue using #191.

**Comment by prasadtalasila** [comment]
PR #184 merged with dev branch. The work is complete.
